### ISSUE TITLE
문제 출제사이트 이전

### ISSUE THREAD

**Issue by realnumber** [wavetogether/wave_algorithm_challenge#8]
[hackerrank](hackerrank.com)는 
1. 문제 제출 후 실행 속도나 메모리 점유율 등의 유용한 정보를 볼 수가 없고 
2. 테스트의 수가 20-30개 밖에 안되서 모든 코너 케이스들을 커버하지 않는다는 한계가 존재하는데

[leetcode](https://leetcode.com/), [백준](https://www.acmicpc.net/) 혹은 다른 사이트를 시도해보는 건 어떨까요?

**Comment by BongrammerSH** [comment]
hackerrank 테스트 케이스도 살펴봤는데 테스트 케이스도 잘 못 만들고 엉망인 것 같아요. 그리고 실행 속도나 메모리 점유율 볼 수 없는 것도 아쉽고,
하스켈만 포기한다면 leetcode 좋을 것 같습니다.

**Comment by realnumber** [comment]
@artechventure 하스켈 포기해도 되나요?

**Comment by realnumber** [comment]
16일 문제부터 leetcode에서 출제하겠습니다!
